-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- The config is split into multiple modules inside configs/.
-- Create your files separately and then require them like this:
-- require("myColors")
--
-- Each require() call is its own Lua scope, so a syntax error in one
-- module will not stop the other modules from applying.

require("configs.monitors") -- Display configuration
require("configs.programs") -- Shared app variables (terminal, file manager, menu)
require("configs.autostart") -- Autostart apps on session start
require("configs.environment") -- Environment variables
require("configs.permissions") -- Permission policy (e.g. screenshots, plugins)
require("configs.theme") -- General look and feel, curves, animations
require("configs.layouts") -- Dwindle / Master / Scrolling layout settings
require("configs.misc") -- Miscellaneous options
require("configs.input") -- Keyboard, touchpad, gestures, devices
require("configs.keybindings") -- Key bindings
require("configs.window-rules") -- Window / workspace / layer rules
